
// -*- C++ -*-
// $Id: Version.h 97637 2014-02-28 07:47:44Z johnnyw $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define DAnCE_MAJOR_VERSION 1
#define DAnCE_MINOR_VERSION 2
#define DAnCE_BETA_VERSION 5
#define DAnCE_VERSION "1.2.5"
