//
// $Id: test.idl 97503 2014-01-06 09:47:50Z mcorino $
//

module Test
{
  struct RecursiveStruct3;
  typedef sequence<RecursiveStruct3> RecursiveStructSeq3;

  union RecursiveUnion3 switch(short)
  {
          case 0: short a;
          case 1: RecursiveStructSeq3 b;
          case 2: RecursiveStructSeq3 c;
  };
  struct RecursiveStruct3
  {
          RecursiveUnion3 uni;
  };

};
